### ISSUE TITLE
Calling OData v3 Functions/Actions

### ISSUE THREAD

**Issue by superstevek** [Breeze/breeze.js#100]
Is it possible to make use of OData Actions/Functions through Breeze. We have a few bits of functionality that are exposed through OData (v3) Actions but cant see how to get breeze to use them?

**Comment by wardbell** [comment]
Please explain why you think this is something Breeze should do? 

Actually, I'd love for someone to explain why this is something OData should do.  OData (and Breeze) are data management libraries. Actions ... even actions with server-side data side effects ... seem to me a separate concern.

The results of the action (if any) don't naturally flow back to the client in any generalizable way. The results might be entities or have entities ... but more often they are some kind of arbitrary response.

You should have no trouble hitting the action API endpoint directly using the AJAX component of your choice (e.g., $http). 

I just don't see how adding support for this to the library (OData or Breeze) does anything but add complexity. 

But I welcome a counter argument. If there is something that breeze could be doing that is easier and better than calling the endpoint directly (even the OData action endpoint), please let us know so that we can consider adding a new feature.

Thanks.

**Comment by superstevek** [comment]
Ward you make a good point.

We have an MVC app which was partially migrated to a standard WebApi, which we are then migrating to an OData api and hooking up to breeze (for 1 client, we may have other clients not using breeze). We migrated these old actions on to the OData api and tried calling them from Breeze without really assessing if that was still the most appropriate way of achieving that functionality.  I think our cleaner (and better) solution will be to have breeze do the logic that was in the function and then persist those changes to the database with the rest of the batch as normal.

Thanks for your thoughts, they have been very useful (and saved me some pain)

**Comment by wardbell** [comment]
Excellent. Please do write back if you change your mind ... or have further thoughts to share from your experience.

Meanwhile, I will close this issue.
