### ISSUE TITLE
Question: Breeze angular 2 bridge?

### ISSUE THREAD

**Issue by ganySA** [Breeze/breeze.js#117]
Hi

Angular 2 is starting to take shape really nicely, i (and i am sure others) would love to start moving over to it but i dont want to move away from breeze.

Any chance we can have a beta bridge adapter?

**Comment by marcelgood** [comment]
A lot of things are still rapidly changing in Angular 2 (it's still alpha at best), but as things start to get more stable we'll probably make something available. At this point I would not encourage to write a real application using the alpha builds of Angular 2.

**Comment by wardbell** [comment]
For example, the A2 http story is being rethought as I write and APIs are up in the air. That matter a lot to a data library like breeze. 

A naive port to A2 will not be hard, probably a few lines. A smart adapter that ties into A2 change detection will tale a bit more effort.

We will do it. Too soon right now

**Comment by cime** [comment]
Angular 2.0 is now in beta. Is there any plan for a bridge for it?

**Comment by ganySA** [comment]
+1

**Comment by jtraband** [comment]
We are working on one now. Please stay tuned.

**Comment by ganySA** [comment]
Fantastic !

**Comment by brikibsw** [comment]
Any news ??

**Comment by thevictor13** [comment]
As a big fan of Breeze and the upcoming Angular 2, I'm also curious about when we can get our hands on an angular 2 compatible version. I see you guys are busy working on angular.io (and who knows what else), and I honestly hope that once you've got a little more time you intend to get back to Breeze. I believe its pretty mature by now by experience, so the majority of the work would be to keep it up-to-date.

As a start, the previously mentioned naive port and a TS definition file would be awesome, because if we had that then we - Breeze supporters - could start using angular 2 and provide valuable feedback helping to smooth out the rough edges - which feedback might be too early for you understandably if you're busy, but I cannot possibly know that... :)

PS: Would be happy to contribute but TS and A2 is something I've just started to pick up on...

**Comment by jtraband** [comment]
Thanks for feedback, and just to be clear breeze works TODAY with angular2.  We know this because we are actually building an angular2/breeze app for one of our clients.  At this point there are really only two sticking points, neither of which is large. You need to use Q for promises ( via standard breeze configuration) and we've created a small shim to convert Q promises to match Promises that angular2 uses and you need to use jquery for ajax calls ( again via standard breeze configuration). Both of these are because of parts of angular2 that are still in flux.  The first of these is because we are waiting to see how Observable vs Promise issues work out for the angular http service. and the 2nd of these is because the angular2 http service itself is not yet complete. And ... there is already a complete TS definition for breeze here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/breeze/breeze.d.ts  Hope this helps.

**Comment by ganySA** [comment]
Hi

@jtraband Thank you for the response - are you using the same breeze bridge adapter for promises as for angular 1?

Also is there an example of the configuration that you have used - I think we could probably close this issue and answer a lot of questions with a little example on how people can start playing around with breeze with angular 2 (configuration, adapter etc)

**Comment by JaFonz** [comment]
@ganySA This worked for me - https://mobile.twitter.com/wardbell/status/673263214050734082

**Comment by wardbell** [comment]
Yes, that `q.js` adapter in that plunker gets you over the promise hump. We'll get to replacing `jQuery.ajax` for HTTP with Angular 2's own `http` client "soon". 

As Jay says, we'll have to figure out how much we want to play the Observable game versus sticking with promises for server responses. It shouldn't hinder your development as long as you do as we recommend: wrap your `EntityManager` interactions in an Angular service that insulates components from the details of data access.

**Comment by christianacca** [comment]
So @wardbell what's your current thinking about Observables and whether they are a good fit for breezejs?

**Comment by christianacca** [comment]
> As Jay says, we'll have to figure out how much we want to play the Observable game versus sticking with promises for server responses.

If you choose promises then there **won't be a way of cancelling the http request** right?

**Comment by dsoltesz** [comment]
any update on replacing  jQuery.ajax  for HTTP with Angular 2's own  http  client?

**Comment by marcelgood** [comment]
Beta support for Angular 2 has been released. 

https://github.com/Breeze/breeze.bridge.angular2/blob/master/README.md

**Comment by christianacca** [comment]
FYI, I've posted a follow up question of better support for angular 2 over in the bridge repo: https://github.com/Breeze/breeze.bridge.angular2/issues/1
