### ISSUE TITLE
createEntity() returns wrong entity type when using inheritance

### ISSUE THREAD

**Issue by danielgerlag** [Breeze/breeze.js#133]
If you have multiple entities that inherit from a base entity, calling createEntity() returns wrong entity type when trying to create one of the derived entities.

**Comment by art-ist** [comment]
+1

**Comment by danielgerlag** [comment]
Yip, I think this is an issue with BreezeJS itself, you shouldn't have to implement the workaround you've provided, createEntity should return the correct class IMHO.

**Comment by steveschmitt** [comment]
Currently, the value returned by the constructor is the entity, and the constructor is tied to the (last) type that it was registered with.  Breeze would need to wrap the provided constructor, as @art-ist is doing, for the provided constructor to be used for more than one type.  

This would be a breaking change for anyone who expects their provided constructor to be used directly, and not wrapped.

I've added a console warning if the same constructor is used twice.

**Comment by marcelgood** [comment]
You are not setting up the prototype chain in your hierarchy. If you have inheritance, you need to setup the prototype chain, so that your derived object actually inherits properties and methods from the parent object. Just calling the base ctor from your derived ctor is not correct inheritance. Breeze handles prototype chains properly, but yes you have to rebuild your inheritance on the client in Javascript to reflect the inheritance you have on the server.

This is a lot easier with Typescript btw, where you can actually define classes with inheritance and the Typescript compiler handles the ugly setup of the prototype chain.
