### ISSUE TITLE
get 'undefined' saveResult.entities after saveChanges

### ISSUE THREAD

**Issue by xixihaha1992** [Breeze/breeze.js#153]
I tried to update one entity in my angularjs client using breezejs library. After calling saveChanges(), it can actually save back in the server and fetched on the client. However, the server did not return the response back. The saveResult.entities is undefined and pop up an error for me. When I took a look at the docs, it mentions 'Some service APIs do not return information about every saved entity. If your server doesn't return such information, you should add the pre-save, cached entity to saveResult.entities yourself'. Could anyone provide an example of how to do this?

**Comment by rastographics** [comment]
What is your server language? Can you look at the network request in Chrome dev tools and see what the actual response from server is?

I've had weird errors before on my server-side (.net) that resulted in breeze returning invalid save result. But the problem was unrelated server error and not breeze.

**Comment by steveschmitt** [comment]
Question moved to [StackOverflow](http://stackoverflow.com/questions/37714544/get-undefined-saveresult-entities-after-savechanges-breezejs)
