### ISSUE TITLE
Breeze date fields and UI Bootstrap DateTime Picker doesn't work well.

### ISSUE THREAD

**Issue by marcbernal** [Breeze/breeze.js#166]
While using UI Bootstrap Datepicker Popup and data retrieved through Breeze, the user is not able to manually enter a date. When clicking on the date field, nothing is wrote on the input, if you press backspace if a date is informed, all the date numbers are removed and doesn't allow to write anymore.

Everything works fine selecting the date through the date picker and when assigning the ngModel to a scoped new variable date. Only fails when assigning the ngModel to a Breeze entity date field.

**Comment by marcelgood** [comment]
Have you checked the validation errors on the entity? My guess is that the datepicker is setting invalid values while entering the date.

**Comment by marcbernal** [comment]
Hey, thank you for your response. I will check it, but I guess it is another issue, because the datepicker sends a correct date, and I can not input any kind of data to the field, any pressed key is deleted.

**Comment by marcelgood** [comment]
Yep, you are running into validation issues. This is expected behavior. Basically, what's happening is that while you are typing the date, it is not yet a valid date, but the data binding is trying to set the entity's data property with the incomplete date value. Breeze rejects that, because it's not a valid date and leaves the value unchanged, so then data binding reads the value back, which is still the old value and overrides your input. 

This only works if you bind the datepicker to a string property, so you can accept any input and then parse it at the end. Most of the time what we do is bind datapickers etc to properties in the viewmodel and then once the complete date has been entered and it can be parsed successfully, then we set the value of the entity's data property. You get this same issue with other formatted inputs. For example if you have a property that only accepts numbers and you bind it to the text box, and then the user types letters. That causes the validation errors and rejection of the value. 

Generally, you can't bind free text input fields directly to properties on the entity unless they are string properties, because the setters reject any value that is not valid. 

Another option is to configure the data binding such that it doesn't set the value until you tab out of the datepicker. The default behavior of most controls is such that it sets the value after each keystroke and that's causing these types of issues.

**Comment by marcelgood** [comment]
Can you point me to the actual datepicker you are using? It probably has an option to configure it so it doesn't pass through and invalid value. Or there are two properties that you can bind to. The text and the actual value. Text would allow invalid input, but value would only be set if the input is a valid date.

**Comment by marcbernal** [comment]
Hi Marcel, thank you for your time and your help.

You are right, I'm remembering long time ago we had a similar issue with an input mask, and we had to workaround it by using a string variable and then assigning it to the entity when saving. This time, we can not use this workaround, because we have a lot of datetimes that the user needs manual input. Based on your answer if the datepicker doesn't allow by it's own way to do that, I will try to create a directive that simulates what you are saying, store the value in a string, and when user tabs or on losing the focus it store on the entity.

We are using the last version of UI Bootstrap DateTime Picker popup: https://angular-ui.github.io/bootstrap/#/datepickerPopup

And again, thank your for your quick answers, you are doing a great job with Breeze.

**Comment by marcbernal** [comment]
I finally wrote a directive to handle this. 

Thank you for your help and tips @marcelgood
