### ISSUE TITLE
Module cannot import itself - Ionic2 app

### ISSUE THREAD

**Issue by rastographics** [Breeze/breeze.js#170]
Trying to get breeze going in Ionic2 rc1.

Getting this error when trying to `ionic serve` or `ionic build` the project:

`bundle failed: A module cannot import itself (C:\repos\Xtinguishers\tech-app-v2\node_modules\breeze-client\breeze.debug.js)`

The only time I reference breeze in my project is through importing the Breeze Angular2 Bridge module as seen in the latest TempHire, and this line in my data service:

`import {EntityManager,EntityQuery,MetadataStore,NamingConvention,promises} from 'breeze-client';`

Using angular 2.1 and ionic rc1, breeze 1.5.14, and breeze-bridge-angular2 0.3.3

There are no compile errors. only this build error.

**Comment by steveschmitt** [comment]
The problem is that `breeze.debug.js` includes adapters that import breeze.  You can fix this by using `breeze.base.debug.js`, which does not include the adapters.  See [temphire.angular2](https://github.com/Breeze/temphire.angular2/tree/master/TempHire) for an example of this.

**Comment by marcelgood** [comment]
There are a few steps to make this work. First, you have to configure an alias for breeze-client, so rollup uses breeze.base.debug.js instead of breeze.debug.js.

https://github.com/Breeze/temphire.angular2/blob/master/TempHire/rollup.js#L16

Then you have to import all the adapters your app uses.

https://github.com/Breeze/temphire.angular2/blob/master/TempHire/app/core/services/entity-manager-provider.ts#L7

And then configure them.

https://github.com/Breeze/temphire.angular2/blob/master/TempHire/app/core/services/entity-manager-provider.ts#L28

**Comment by rastographics** [comment]
Thank you!!

Just some notes for anyone else trying to do this, in addition to @marcelgood post, make sure you also setup your rollup.js config with the same [named exports that TempHire has](https://github.com/Breeze/temphire.angular2/blob/master/TempHire/rollup.js#L32)

**Comment by rastographics** [comment]
Since Ionic2 has moved back to using Webpack instead of rollup, this is not an issue anymore for Ionic projects so I'm going to close it.
