### ISSUE TITLE
isNavigationPropertyLoaded undefined after fromEntityNavigation

### ISSUE THREAD

**Issue by randellhodges** [Breeze/breeze.js#190]
I may be doing this wrong, of have wrong expectations. In the following code (adjusted to be included in the post) I don't expect it to try to fetch inside ensureLayout. I expect 'not fetched' alert.

The call the ensureCharacter works and I can see in the json response that the tabs of the specified layout are returned (and none of them for the other layouts, which is what i want). It seems like fromEntityNavigation isn't correctly setting the isNavigationPropertyLoaded in this case.

I guess I could set it myself. Is this a correct assumption that it should set it?

This isn't a full example, but it should show the pattern I am attempting.

```
function ensureCharacter(id, layoutId) {

	// The withParameters just informs the server that I want it to "expand" the tabs of a specific layout
	var query = breeze
		.EntityQuery
		.fromEntityNavigation(service.character, 'layouts')
		.withParameters({ layoutId: layoutId });

	manager
		.executeQuery(query)
		.then(function () {
			// If I set a breakpoint here, I can see that
			// service.character.layouts[matched by id].tabs has data
			// so I expect this next method to not fetch
			ensureLayout(layoutId);
		})
		.catch(function () {
			alert('TODO: Layout fetch failed')
		});
}

function ensureLayout(id) {	
	
	var found = service.character.layouts.find(function (c) { return c.id === id });
							
	if (found.entityAspect.isNavigationPropertyLoaded('tabs')) {
		service.layout = found;
		alert('not fetched');
	}
	else {
		found
			.entityAspect.loadNavigationProperty('tabs')
			.then(function () { 
				service.layout = found;
				alert('fetched'); 
			});
	}
}

```

**Comment by marcelgood** [comment]
In your case, Breeze doesn't know yet that the `tabs` property is loaded, because if I understand correctly, you are not doing an `expand` on the client. You're sending a parameter to the server to let it know to expand.

A navigation property is considered loaded when any of the following three conditions applies. Since you are doing the expand on the server the client should call `EntityAspect.markNavigationPropertyAsLoaded` to let Breeze know that you did load it on your own. 

1) It was fetched from the backend server.
a) This can be the result of an expand query or a call to the EntityAspect.loadNavigationProperty method.
b) Note that even if the fetch returns nothing the property is still marked as loaded in this case.
2) The property is scalar and has been set to a nonnull value.
3) The EntityAspect.markNavigationPropertyAsLoaded was called.

**Comment by randellhodges** [comment]
Thanks. I indeed solved it with the `EntityAspect.markNavigationPropertyAsLoaded` method. It makes sense that without doing an expand on the client side, it can't tell from the returned data if it was already loaded, well, at least not 100% sure that is.
