### ISSUE TITLE
Any Roadmap for the project 

### ISSUE THREAD

**Issue by badre429** [Breeze/breeze.js#196]
breeze.js has a huge potentiel but the way i see in this project on github 
i see its like on maintenance mode 
No roadmap

**Comment by steveschmitt** [comment]
That's a great idea.  What would you like to see on the roadmap?

**Comment by badre429** [comment]
*** we see great potention on breeze it give as the power to make our end user "Happy" specialy with the change traking and bulk saving .... etc ***

## What we need to know is the :

- Future plane for more features ( example using breeze over Graphql endpoint if its possible) 
- LTS (long time support ) version

**Comment by ofirgeller** [comment]
Make compatible with webpack.

**Comment by marcelgood** [comment]
@ofirgeller What issues are you running into with webpack? We are aware that Breeze can't resolve the OData dependency when using webpack, but otherwise it works fine with webpack. We are working on a fix. 

I've just migrated our Angular reference example to webpack. Meant to do that for a while. We've also been using webpack in all of our projects for a while now, and have not run into any issues. Take a look at the example.

https://github.com/Breeze/temphire.angular

**Comment by ofirgeller** [comment]
@marcelgood  When I tried to use breeze Q was missing. i tried adding it myself, no dice, tried adding it (Q)as a script reference. did not work. I think it has something to do with window being undefined when breeze looks for dependencies. a got around that problem be setting the q implicitly. but then had the same problem with jQuery. Since there is no method to config jQuery I had to bundle the 3 scripts (Q, jQuery, breeze) inside the same file.

One more item on my wise list  would be removing jQuery as dependency if you are only targeting ever-green browsers. 

Will take a look at the example and look for the diff.

**Comment by marcelgood** [comment]
@ofirgeller The example doesn't use Q at all. Angular uses ES6 promises. It's replacing the Q dependency with ES6 promises during the configuration step. I believe you are running into the same issue as others have run into with OData. The way Breeze resolves dependencies doesn't work with webpack currently. The fix should resolve this.

**Comment by ofirgeller** [comment]
@marcelgood  If oData is the default then I must be using it. if not, I am not. if the example is not using Q then I is not relevant to my problem. since the error I get is that Q is not found. if I force feed Q into breeze by calling setQ  then the I get an error about jQuery not being found. maybe I need to read the get started guide again, when I first setup breeze it was along side angular, this time it's without so There might be many differences I am not aware of.

**Comment by marcelgood** [comment]
@ofirgeller Breeze is indeed having legitimate issues with resolving external dependencies when used with webpack. In case of Angular, we replace Q with ES6 promises and jQuery.ajax with Angular http, therefore these issues don't occur and we are only now becoming aware of them as people are trying to use webpack with frameworks other than Angular.

**Comment by ofirgeller** [comment]
@marcelgood  Cool, I was starting to worry I was just adding noise to the discussion. I'l keep using breeze in the same way I am right now until there is some update. ideally for me breeze will use native promises + fetch and not have any dependencies built in on any specific library (that does not necessarily follow web standards ), with people that need to support older browsers being able to (and responsible for ) adding poly-fills to meet the requirements.

**Comment by gmareater** [comment]
an update would be nice
your recent version for .netCore isn't what it should be, late update and no actual support
so please provide Information about future, It really seems project is dead
Hope to be wrong

**Comment by flyfishMT** [comment]
Any update on this? I am struggling with webpack, breeze, jquery, knockout. I've replaced Q with an ES6 shim, but breeze can't resolve jquery and while debugging I see that ko will be unresolved next.  breeze expects them on global.window, I am using imports-loader to add window to global object when breeze is loaded but it must occur prior to jquery and ko being added to window because they aren't there. I've been getting a "unable to locate jquery" message.
