### ISSUE TITLE
Question: EF Core 2.0 support?

### ISSUE THREAD

**Issue by malichishti** [Breeze/breeze.js#203]
Hi,

In reference to **Breeze.Composite.AspNetCore.EF6** i would like to know when a complete .Net Core server is expected to be available i.e. which is not dependent on .Net Full Framework? Given that [EF Core 2.0 preview 2](https://blogs.msdn.microsoft.com/dotnet/2017/06/28/announcing-ef-core-2-0-preview-2/) is out.

Regards,
Ali

**Comment by sp00ky** [comment]
With a .NET Core 2.0 project on the horizon in which I'd like to use Breeze, this question is on my mind as well.

**Comment by IngoBleile** [comment]
Here as well!

**Comment by markarnolditpro** [comment]
Also very interested.

**Comment by josundt** [comment]
Waiting for this as well! 👍

**Comment by jtraband** [comment]
Starting on this now. Will post back as we make further progress.

**Comment by IngoBleile** [comment]
Hi, any news on that?

**Comment by steveschmitt** [comment]
Yes, we have working code now.  We just need to create the nuget packages.

On Jan 30, 2018 5:57 PM, "IngoBleile" <notifications@github.com> wrote:

Hi, any news on that?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Breeze/breeze.js/issues/203#issuecomment-361578439>,
or mute
the thread

**Comment by nkada** [comment]
Hi, Any futher update on this?

**Comment by sp00ky** [comment]
Still no word on Breeze for EF Core?

**Comment by flieks** [comment]
@steveschmitt Any update ?
Thanks

**Comment by steveschmitt** [comment]
EF Core 3.1 and .NET 5 support is released and available on nuget.  Look for Breeze.Persistence packages.
