### ISSUE TITLE
Required validator on guid property prevents saving if navigation property is not expanded

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze.js#232]
Consider the following metadata : 

![image](https://user-images.githubusercontent.com/4160415/135100565-c6b09e1c-1888-411c-b970-4843320da21c.png)

OtherLanguagesInterventionLevelId is a required field and there is also the navigation property OtherLanguagesInterventionLevel, with no validators.

When trying to save my object after changing the value of OtherLanguagesInterventionLevelId, I get a client-side validation error on OtherLanguagesInterventionLevel that says it is a required field. Its value is null because I did not expand it from server-side, however I would expect the save to be successful.

![image](https://user-images.githubusercontent.com/4160415/135101135-7a198922-7be3-4438-b80a-33984649eb87.png)

That's not the expected behavior right ?

**Comment by graphicsxp** [comment]
After some more investigations, I confirm the problem is happening with all my navigation properties for which the foreign key guid is non-nullable.
Validator is added client-side by breeze on the navigation property which makes it not possible to save the entity if the navigation property is null (athough the guid is not null). Could you take a look please ?

**Comment by marcelgood** [comment]
That is odd. Breeze out of the box doesn't add validators to the navigation property, only the FK property, because the FK property corresponds with the DB column. The navigation property is a calculated property based on the FK property and is usually save to leave null, even if the FK is required. I haven't seen this in any of our projects and even the metadata you posted above doesn't have any validators for the navigation property. Are you sure it's not added manually by your code or some other process. If you inspect the metadata right before the save, is there a validator for the navigation property?

We would need a small sample that reproduces this issue to investigate further.

**Comment by graphicsxp** [comment]
To answer your question, yes the validators on the navigation properties are in the metadata just before the save  :

![image](https://user-images.githubusercontent.com/4160415/135404731-da45caf0-ae26-4da0-9355-9d7a47332c87.png)

I do not add these validators to the metadata, that's definitely not my code. We will try to put together a repro however in the meantime these are the versions we use, maybe you can take a quick look to see if there is something wrong in the code :   

- breeze server side :  Breeze .net core 5.0.5
- breeze client side:  2.1.2

**Comment by graphicsxp** [comment]
you are absolutely right. The required validator on the np was added by me... I totally forgot about this bit of code in the metadataStore initialization and removing this code seems to fix the problem. Sorry about that.
