### ISSUE TITLE
iOS 5.1.1 

### ISSUE THREAD

**Issue by markvp** [Breeze/breeze.js#27]
I am using BreezeJS in my web app.

When I call `manager.saveChanges()` in the web app via an iPad 1 (Model MC349X with iOS v5.1.1), I get an error in the Safari Debug Console Log:

```
TypeError: 'undefined' is not a function
```

After line by line console log debugging (a real nightmare on iOS v5.1.1 Safari!), I have isolated the cause as being this line of code in breeze.debug.js:

```
this._hasChangesAction = this._hasChangesAction || function () {
    this._setHasChanges(null);
    this.entityChanged.publish(ecArgs);
}.bind(this);
```

Essentially, it appears that Safari in iOS v5.1.1 does not implement the bind prototype function (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind).

The site above references a polyfill:

```
if (!Function.prototype.bind) {
  Function.prototype.bind = function (oThis) {
    if (typeof this !== "function") {
      // closest thing possible to the ECMAScript 5
      // internal IsCallable function
      throw new TypeError("Function.prototype.bind - 
           what is trying to be bound is not callable");
    }

    var aArgs = Array.prototype.slice.call(arguments, 1), 
        fToBind = this, 
        fNOP = function () {},
        fBound = function () {
          return fToBind.apply(this instanceof fNOP && oThis
                 ? this
                 : oThis,
                 aArgs.concat(Array.prototype.slice.call(arguments)));
        };

    fNOP.prototype = this.prototype;
    fBound.prototype = new fNOP();

    return fBound;
  };
}
```

This polyfill successfully works for me.

Is it worth including this within Breeze or avoiding the use of `.bind`?

**Comment by jvanbouchaute** [comment]
Exactly the same issue when running Jasmine tests with BreezeJS on PhantomJS 1.9

**Comment by wardbell** [comment]
Because pre-2.0 phantom.js lacks `bind` support, I baked a polyfill into the [bardjs](https://github.com/wardbell/bardjs) testing support library for Angular. It makes sense for bard because phantom is inescapable in test environments and few folks have upgraded (or can yet upgrade) to v.2.x.

It doesn't make sense to include this polyfill in breeze which targets modern browsers (even though it is viable with shimmed older browsers).

I updated our [pre-requisites page](http://breeze.github.io/doc-js/prerequisites.html) to call out the need to shim  "*PhantomJS before v.2 and Safari before v.1.5.4*".
