### ISSUE TITLE
Feature Request: a method to unwrap breeze entities.

### ISSUE THREAD

**Issue by dlmanning** [Breeze/breeze.js#37]
As discussed in: http://stackoverflow.com/questions/21049345/breeze-js-using-notracking-not-unwrapping-entities

This would be really great. I'm currently having to individually describe every object in our data tree just to get a plain javascript object copy of an entity.

**Comment by wardbell** [comment]
Closing because there is nothing broken. Perhaps you'd like to have a new Breeze feature. The best place to register that is on [Breeze UserVoice](https://breezejs.uservoice.com/forums/173093-1-breezejs-feature-suggestions).

However, I don't think it is actually that hard to write the unwrapping code you need. Unlike Breeze, you don't need a general purpose solution. You know what model library you are using and you know which properties you want to deserialize.

You can do it in a *general way for your application* by leveraging the metadata for your model in a utility that knows how to "unwrap" certain properties and not others.

Let us know if you need help figuring this out.
