### ISSUE TITLE
Breeze Cannot return extended Entities using queries that have an .expand clause

### ISSUE THREAD

**Issue by roylee0704** [Breeze/breeze.js#61]
I'm using breeze v1.5.0 with Angular(front) and MVC 4.5 + web api 2 + Entity Framework6 at the back.

This is how I extends the entity.
```javascript
 function UserGroup () {
        this.save = function save() {
           //save..
        };
    }

metadataStore.registerEntityTypeCtor('UserGroup', UserGroup);

```
---

When I'm trying to query `UserGroup`(navigation property of  `User`) with `expand()`:

```javascript
breeze.EntityQuery.from('User').using(_this.manager).expand('userGroup');
```

The `UserGroup` instance doesn't consists of `save()` method.

---

This is what I get:

```javascript
UserGroup__cvs_web_Models {

$$hashKey: "011",
_backingStore: Objectabc: (...),

... 

```
Which I discovered there is this namespace of my declared `entity` from .NET: `__cvs_web_Models` attached to the entity name.

**Comment by wardbell** [comment]
First, I don't think you want to add this function to the constructor like that. You want to add it to the **prototype** ... like this.

    function UserGroup () { ... }
    UserGroup.prototype.save = function save() { ... }

Second, I'm wondering why you'd want to put a method named `save` on an entity type. What's the point? What are you going to do with it? There is an `EntityManager.saveChanges` and we **strongly recommend** that you call that method (within a client service) rather than ask the entity itself to perform any persistence activity. Your move is more in keeping with the "ActiveRecord" patter in which entities are self-persisting. That's not a good pattern for complex data scenarios in which multiple entities are saved together in the same transaction. For that kind of thing ... the kind of thing that Breeze is designed for ... you need the "UnitOfWork" pattern in which an external component (the `EntityManager`) tracks and persists change-sets.

But most important for this question, I can't repro the error you've described. In fact, I have a [DocCode test](https://github.com/Breeze/breeze.js.samples/blob/master/net/DocCode/DocCode/tests/entityExtensionTests.js#L149) that appears to cover the scenario you've described ... and it passes. Here it is:

    asyncTest("can add function via constructor (not prototype)", function () {
      expect(2);
      var store = cloneModuleMetadataStore();

      var Customer = function () {
        this.foo = function () { return 'foo'; }
      };
      store.registerEntityTypeCtor('Customer', Customer);

      var cust = store.getEntityType('Customer').createEntity();

      equal(typeof cust.foo, 'function', "should have 'foo' function via constructor");

      var manager = newEm(store);
      EntityQuery.from('Orders').take(1).expand('Customer')
        .using(manager).execute()
        .then(function (data) {
          var order = data.results[0];
          cust = order ? order.getProperty('Customer') : {};
          equal(typeof cust.foo, 'function',
            "should have 'foo' function after expand query");
        })
        .catch(handleFail).finally(start);
    });

**Comment by steveschmitt** [comment]
If your entity is coming back as `UserGroup__cvs_web_Models` instead of `UserGroup`, that would certainly cause problems, because your entity constructor won't get used.  I don't know what would cause this; you should ask a question on [StackOverflow](http://stackoverflow.com/questions/ask).

**Comment by wardbell** [comment]
Why would that cause a problem, Steve? 

Ah ... I think I understand!

The name `UserGroup__cvs_web_Models` is generated by Breeze when it uses the *default Breeze entity constructor* to create the entity instance.

But you registered a constructor function named `UserGroup`. Had Breeze used your constructor, the debugger would have displayed the entity as an instance of "UserGroup", not "UserGroup__cvs_web_Models". 

I think this "proves" that Breeze is not using your constructor and therefore you are not getting the extended methods.

You are registering your constructor with a metadataStore ... but is it the *right* metadataStore! Where did you get that`metadataStore` instance with which you registered?

One way to find out is to set a breakpoint where you `EntityManager` makes the call and inspect it's `metadataStore` property.  I'll bet it is not the same metadataStore object that you used in your registration.

**Comment by wardbell** [comment]
No follow-up from you. There does not appear to be a Breeze issue here. Closing until we hear otherwise from you.

**Comment by roylee0704** [comment]
@wardbell , @steveschmitt  Oh, I finally understand the problem now! Yes, it is not a Breeze issue here but rather the sequence of how I register each of the constructor function with `metadataStore`.
