### ISSUE TITLE
saveChanges fails when deleting & modifying a many-to-many table in one saveBundle

### ISSUE THREAD

**Issue by anicoll** [Breeze/breeze.js#89]
I am trying to delete a record in a many-many table that has a Unique index on it. Therefor if a component is being added to a list the order has to be incremented by one or the back-end wont allow it to be saved to the DB.

My problem comes in when I delete one of these components in the list I am also modifying any components with and Order higher than it as to not have a gap in the order of these components.

Scenario:

The many to many table is populated with 5 components with unique index's as are the componentId's unique. The components entityAspect is set to deleted (No save has taken place yet)

I delete the third component thus component 4 & 5 will have there index reduced by 1 each so that the new index will be 1234 and not 1245. This is done is JS and once this is done I then call my service which saves all the changes.

I have also tried to overwrite the saveMap.

    protected override Dictionary<Type, List<EntityInfo>> BeforeSaveEntities(Dictionary<Type,     List<EntityInfo>> saveMap)
    {
        saveMap[typeof(ManyToManyBdo)] = saveMap[typeof(ManyToManyBdo)].OrderBy(info => info.EntityState).ToList();
        return base.BeforeSaveEntities(saveMap);
    }

This doesn't seem to change the way breeze executes though.

**Comment by steveschmitt** [comment]
Do you think the problem is in the order that the entities are persisted?  Is there an exception thrown?

**Comment by anicoll** [comment]
Yes thats the problem, atleast I think it is which is what I thought the saveMap was supposed to change if I ordered it but doesnt seem to.
![grid](https://cloud.githubusercontent.com/assets/9248578/7280108/971d133c-e918-11e4-89b9-fd11b047dc82.png)
This grid shows you the design of my table.

If I delete the second row I also update the execution order for that specific Rule(The order is Unique per rule so then the will(SHOULD) be the table after the update but because of my unique Key on the table my DB wont allow for such an update.

![grid](https://cloud.githubusercontent.com/assets/9248578/7280202/1652b13e-e919-11e4-9883-eb77439a80c7.png)

This is what it should be after the save.

**Comment by steveschmitt** [comment]
The order of saves is not determined by the saveMap, but by the underlying persistence mechanism (Are you using Entity Framework?).  Normally, it's safe to do the Insert and Update operations first, and the Delete operations last.  In your case, the Delete would have to be done before the Update to prevent two rows from temporarily having the same RuleId + OrderId combination.

**Comment by anicoll** [comment]
I am using Entity Framework yes.

**Comment by jtraband** [comment]
What is the exact exception that is being thrown? Which column in the database is the exception referring to?  If the 'ID' column is your primary key, do you also have a database constraint on the 'Order' column?

**Comment by anicoll** [comment]
Yes there is a constraint on the order. 
Order is Unique per RuleId.
ComponentId is Unique per RuleId.

So if you look at my above post with the tables, if I delete the second row the Order Column updates too.

**Comment by jtraband** [comment]
Ok, I think i understand your problem.  The issue is that by adding these constraints you have created the possibility that your data needs to be saved in an order that is different from what the Entity Framework determines.  Basically EF looks at primary keys and foreign keys ( and changes to these values) to toposort the entities in any save operation.  It then performs saves in this order.  EF does not provide any mechanism for explicitly ordering its save operations.  

Because EF does not see or use your constraints it does not realize that its save order will not work for your use case.  This is not something breeze can do anything about.

However, there is another approach that should work.  
1) Do not attempt to 'fixup' the 'order' column on the client. Just leave it alone.
2) Remove the database constraint on the 'order' column.
3) Create a database trigger that recalcs the 'order' column after any save.
4) Since breeze automatically requeries the database after a save, it should pick up the reordered values and return them to the client.

Hope this makes sense.

**Comment by anicoll** [comment]
Thanks for your help.I'll see what I can do with this. Hopefully in the next EF release this will be addressed or at least accessible.
